// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import TopNavigation, { NAVIGATION_ACTIONS, TOP_NAVIGATION_SHORTCUTS_KEY } from '../../src/TopNavigation'

beforeEach(() => {
  localStorage.clear()
  Object.defineProperty(window, 'innerWidth', { configurable: true, writable: true, value: 1440 })
  Object.defineProperty(window, 'matchMedia', { configurable: true, writable: true, value: undefined })
})
afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.useRealTimers() })

const openConfiguration = (): HTMLElement => {
  fireEvent.click(screen.getByRole('button', { name: '设置' }))
  fireEvent.click(screen.getByRole('menuitem', { name: '配置快捷入口' }))
  return screen.getByRole('dialog', { name: '配置快捷入口' })
}

describe('top navigation', () => {
  it('exposes the primary views and pending count, with two default shortcuts', () => {
    const onNavigate = vi.fn()
    render(<TopNavigation view='attention' pendingCount={123} onNavigate={onNavigate} />)
    const overview = screen.getByRole('button', { name: 'Agent 总览' })
    const attention = screen.getByRole('button', { name: '处理中心' })
    expect(attention).toHaveAttribute('aria-current', 'page')
    expect(attention).toHaveTextContent('99+')
    expect(within(attention).getByLabelText('123 个待处理项')).toBeVisible()
    fireEvent.click(overview)
    fireEvent.click(attention)
    const shortcuts = screen.getByRole('group', { name: '快捷入口' })
    expect(within(shortcuts).getAllByRole('button')).toHaveLength(2)
    fireEvent.click(within(shortcuts).getByRole('button', { name: '安全规则' }))
    fireEvent.click(within(shortcuts).getByRole('button', { name: '关键词续跑' }))
    expect(onNavigate.mock.calls).toEqual([['overview'], ['attention'], ['approval-rules'], ['continue-keywords']])
  })

  it('opens menus immediately, moves keyboard focus and makes closing surfaces inert', () => {
    vi.useFakeTimers()
    const onNavigate = vi.fn()
    const onMenuOpenChange = vi.fn()
    const { container } = render(<TopNavigation view='audit' pendingCount={0} onNavigate={onNavigate} onMenuOpenChange={onMenuOpenChange} />)
    const statistics = screen.getByRole('button', { name: '统计' })
    expect(statistics).toHaveClass('active')
    fireEvent.keyDown(statistics, { key: 'ArrowDown' })
    expect(screen.getByRole('menuitem', { name: '审计' })).toHaveFocus()
    expect(onMenuOpenChange).toHaveBeenLastCalledWith(true)
    fireEvent.keyDown(document.activeElement!, { key: 'ArrowUp' })
    expect(screen.getByRole('menuitem', { name: 'Token 用量' })).toHaveFocus()
    fireEvent.keyDown(document.activeElement!, { key: 'Home' })
    expect(screen.getByRole('menuitem', { name: '审计' })).toHaveFocus()
    fireEvent.keyDown(document.activeElement!, { key: 'End' })
    fireEvent.keyDown(document.activeElement!, { key: 'Escape' })
    expect(statistics).toHaveFocus()
    expect(screen.queryByRole('menu', { name: '统计' })).not.toBeInTheDocument()
    expect(container.querySelector('.motion-presence[data-open="false"]')).toHaveAttribute('inert')
    expect(onMenuOpenChange).toHaveBeenLastCalledWith(false)
    act(() => { vi.advanceTimersByTime(100) })
    expect(container.querySelector('[role="menu"]')).not.toBeInTheDocument()
    fireEvent.keyDown(statistics, { key: 'ArrowUp' })
    expect(screen.getByRole('menuitem', { name: 'Token 用量' })).toHaveFocus()
    fireEvent.click(document.activeElement!)
    expect(onNavigate).toHaveBeenCalledWith('tokens')
    expect(statistics).toHaveFocus()
    expect(statistics).toHaveAttribute('aria-expanded', 'false')
  })

  it('keeps a single menu open, routes every setting and closes on outside interaction or focus leaving', () => {
    const onNavigate = vi.fn()
    render(<><TopNavigation view='overview' pendingCount={0} onNavigate={onNavigate} /><button type='button'>其他操作</button></>)
    fireEvent.click(screen.getByRole('button', { name: '统计' }))
    fireEvent.click(screen.getByRole('button', { name: '设置' }))
    expect(screen.queryByRole('menu', { name: '统计' })).not.toBeInTheDocument()
    expect(screen.getByRole('menu', { name: '设置' })).toBeVisible()
    fireEvent.pointerDown(screen.getByRole('button', { name: '其他操作' }))
    expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    for (const { action, label } of NAVIGATION_ACTIONS.slice(4)) {
      fireEvent.click(screen.getByRole('button', { name: '设置' }))
      fireEvent.click(screen.getByRole('menuitem', { name: label }))
      expect(onNavigate).toHaveBeenLastCalledWith(action)
      expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    }
    fireEvent.click(screen.getByRole('button', { name: '设置' }))
    act(() => { screen.getByRole('button', { name: '其他操作' }).focus() })
    expect(screen.queryByRole('menu')).not.toBeInTheDocument()
  })

  it('persists action selection, reordering, hidden entries and the optional third shortcut across remounts', () => {
    const onNavigate = vi.fn()
    const first = render(<TopNavigation view='overview' pendingCount={0} onNavigate={onNavigate} />)
    const dialog = openConfiguration()
    const select = within(dialog).getByRole('combobox', { name: '快捷入口 1' })
    expect(within(select).getAllByRole('option')).toHaveLength(NAVIGATION_ACTIONS.length)
    fireEvent.change(select, { target: { value: 'tokens' } })
    fireEvent.click(within(dialog).getByRole('button', { name: '下移快捷入口 1' }))
    expect(within(dialog).getByRole('combobox', { name: '快捷入口 1' })).toHaveValue('continue-keywords')
    fireEvent.click(within(dialog).getByRole('checkbox', { name: '显示快捷入口 1' }))
    fireEvent.click(within(dialog).getByRole('checkbox', { name: '显示快捷入口 3' }))
    expect(JSON.parse(localStorage.getItem(TOP_NAVIGATION_SHORTCUTS_KEY)!)).toEqual([
      { id: 'shortcut-2', action: 'continue-keywords', visible: false },
      { id: 'shortcut-1', action: 'tokens', visible: true },
      { id: 'shortcut-3', action: 'llm-review', visible: true },
    ])
    fireEvent.click(within(dialog).getByRole('button', { name: '完成' }))
    expect(screen.getByRole('button', { name: '设置' })).toHaveFocus()
    first.unmount()
    render(<TopNavigation view='overview' pendingCount={0} onNavigate={onNavigate} />)
    const shortcuts = screen.getByRole('group', { name: '快捷入口' })
    expect(within(shortcuts).getAllByRole('button').map((button) => button.textContent)).toEqual(['Token 用量', '审核器设置'])
    fireEvent.click(within(shortcuts).getByRole('button', { name: 'Token 用量' }))
    expect(onNavigate).toHaveBeenCalledWith('tokens')
    const reopened = openConfiguration()
    fireEvent.click(within(reopened).getByRole('button', { name: '恢复默认' }))
    expect(within(reopened).getByRole('combobox', { name: '快捷入口 1' })).toHaveValue('approval-rules')
    expect(within(reopened).getByRole('checkbox', { name: '显示快捷入口 3' })).not.toBeChecked()
  })

  it('manages dialog focus while leaving native select keyboard behavior intact', () => {
    const onMenuOpenChange = vi.fn()
    render(<TopNavigation view='overview' pendingCount={0} onNavigate={vi.fn()} onMenuOpenChange={onMenuOpenChange} />)
    const dialog = openConfiguration()
    const close = within(dialog).getByRole('button', { name: '关闭快捷入口设置' })
    const done = within(dialog).getByRole('button', { name: '完成' })
    expect(close).toHaveFocus()
    fireEvent.keyDown(close, { key: 'Tab', shiftKey: true })
    expect(done).toHaveFocus()
    fireEvent.keyDown(done, { key: 'Tab' })
    expect(close).toHaveFocus()
    const select = within(dialog).getByRole('combobox', { name: '快捷入口 1' })
    act(() => { select.focus() })
    expect(fireEvent.keyDown(select, { key: 'ArrowDown' })).toBe(true)
    expect(fireEvent.keyDown(select, { key: 'Escape' })).toBe(true)
    expect(dialog).toBeVisible()
    fireEvent.keyDown(done, { key: 'Escape' })
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '设置' })).toHaveFocus()
    expect(onMenuOpenChange).toHaveBeenLastCalledWith(false)
    openConfiguration()
    fireEvent.pointerDown(document.querySelector('.top-navigation-dialog-backdrop')!)
    expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  })

  it('collapses secondary shortcuts into an accessible overflow at narrow widths', () => {
    const onNavigate = vi.fn()
    render(<TopNavigation view='overview' pendingCount={4} onNavigate={onNavigate} />)
    expect(screen.getByRole('group', { name: '快捷入口' })).toBeInTheDocument()
    Object.defineProperty(window, 'innerWidth', { configurable: true, value: 760 })
    fireEvent(window, new Event('resize'))
    expect(screen.queryByRole('group', { name: '快捷入口' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Agent 总览' })).toBeVisible()
    expect(screen.getByRole('button', { name: '处理中心' })).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: '更多快捷入口' }))
    fireEvent.click(screen.getByRole('menuitem', { name: '安全规则' }))
    expect(onNavigate).toHaveBeenCalledWith('approval-rules')
    fireEvent.click(screen.getByRole('button', { name: '更多快捷入口' }))
    Object.defineProperty(window, 'innerWidth', { configurable: true, value: 1440 })
    fireEvent(window, new Event('resize'))
    expect(screen.queryByRole('button', { name: '更多快捷入口' })).not.toBeInTheDocument()
    expect(screen.queryByRole('menu')).not.toBeInTheDocument()
    expect(screen.getByRole('group', { name: '快捷入口' })).toBeVisible()
  })

  it.each(['{invalid', JSON.stringify([{ id: 'shortcut-1', action: 'unexpected', visible: true }]), JSON.stringify(Array.from({ length: 3 }, () => ({ id: 'shortcut-1', action: 'audit', visible: true })))])(
    'falls back to default shortcuts for invalid saved preferences: %s', (saved) => {
      localStorage.setItem(TOP_NAVIGATION_SHORTCUTS_KEY, saved)
      render(<TopNavigation view='overview' pendingCount={0} onNavigate={vi.fn()} />)
      const shortcuts = screen.getByRole('group', { name: '快捷入口' })
      expect(within(shortcuts).getByRole('button', { name: '安全规则' })).toBeVisible()
      expect(within(shortcuts).getByRole('button', { name: '关键词续跑' })).toBeVisible()
    },
  )

  it('keeps settings usable when storage is unavailable and allows every shortcut to be hidden', () => {
    render(<TopNavigation view='overview' pendingCount={0} onNavigate={vi.fn()} />)
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('Storage unavailable') })
    const dialog = openConfiguration()
    fireEvent.click(within(dialog).getByRole('checkbox', { name: '显示快捷入口 1' }))
    fireEvent.click(within(dialog).getByRole('checkbox', { name: '显示快捷入口 2' }))
    fireEvent.click(within(dialog).getByRole('button', { name: '完成' }))
    expect(screen.queryByRole('group', { name: '快捷入口' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '更多快捷入口' })).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '设置' })).toBeVisible()
  })
})
